server:
  port: 8088
spring:
  application: paichong
#  datasource:
#    type: com.alibaba.druid.pool.DruidDataSource
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/myproject?serverTimezone=UTC
#    username: root
#    password: 123456
#    initialSize: 10
#    maxActive: 100
#    minIdle: 10
#    maxWait: 50000
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/myproject?serverTimezone=UTC
    username: root
    password: 123456

mybatis:
  type-aliases-package: com.webmagic.dao
  mapper-locations: classpath:mapper/*.xml
  config-location: classpath:mybatis/mybatis-config.xml