server:
  port: 8088
spring:
  application: ott-clawer

  datasource:
    driverClassName: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@127.0.0.1:1521:orcl
    username: wengwutan
    password: 123456
    initialSize: 10
    maxActive: 100
    minIdle: 10
    maxWait: 50000

mybatis:
  type-aliases-package: com.webmagic.dao
  mapper-locations: classpath:mapper/*.xml
  config-location: classpath:mybatis/mybatis-config.xml